### PR TITLE
Remove values from id resource items

### PR DESCRIPTION
**Pull request by squirly**
An `<Item type="id">` resource cannot have a nested value, see [More Resource Types: ID](https://developer.android.com/guide/topics/resources/more-resources#Id).

This error is causing aapt2 to fail App Bundle creation.

This change ultimately needs to make it's way into `tipsi-stripe`'s `build.gradle`  here https://github.com/tipsi/tipsi-stripe/blob/339cea10bc7c45b341154c37d3ef4d96db6cc906/android/build.gradle#L33.

<details>
  <summary>Click to see compile error</summary>

```
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource compilation failed
Output:  <root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:981: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:982: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:983: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:984: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:985: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:986: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:987: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:988: error: <item> inner element must either be a resource reference or empty.
<root>/node_modules/tipsi-stripe/android/build/intermediates/res/merged/release/values/values.xml:1005: error: <item> inner element must either be a resource reference or empty.
```

</details>

### CODE REVIEW

**Comment by isnifer** [comment]
@ngoryachev please, take a look

**Comment by paintedbicycle** [comment]
Let me know if I can help test this. 

AAPT2 support is stopping me from being able to release my Android app. I'm coming up against this error and it appears this PR might fix it.

**Comment by squirly** [comment]
@ngoryachev BUMP!

**Comment by ThomasGHenry** [comment]
Is this happening?

**Comment by cybergrind** [comment]
Sorry guy for such long review =)

**Pull request merged**
